### ISSUE TITLE
Make Bionic GA

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh-linux-stemcell-builder#157]
#### Prerequisites

- [x] https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/151 needs to be fixed first
- [x] https://github.com/cloudfoundry/bosh-stemcells-ci/pull/3
- [x] Use master agent for bionic: https://github.com/cloudfoundry/bosh-agent/commit/b68c7860102f69578f94be6227222f43a6e71635

#### ToDos
- [x] clarify whether we would continue the same naming pattern as with Xenial -> fine for now
- [x] clarify can we hook up the USN trigger that also creates stories in Director Pivotal Tracker?
- [x] release another release candidate 0.2x -> 0.24, 0.28
- [x] add a >=1.x group to the concourse pipeline
- [x] remove 0.x group/jobs from pipeline
- [x] get a 1.x release cut -> 1.1
- [x] update bosh.io
- [x] announcement sent to cf-dev

#### Acceptance Criteria
- Release Candidates validated
- Bionic Stemcell >=1.x published

**Comment by friegger** [comment]
@ramonskie These can now be removed, can't they?
- https://main.bosh-ci.cf-app.com/teams/main/pipelines/bosh:stemcells:ubuntu-bionic?group=agent-0.x
- https://main.bosh-ci.cf-app.com/teams/main/pipelines/bosh:stemcells:ubuntu-bionic?group=build-0.x

**Comment by ramonskie** [comment]
yes they can will ask @rkoster
