### ISSUE TITLE
Migrate pipeline from VMWare to Community Concourse

### ISSUE THREAD

**Issue by friegger** [cloudfoundry/bosh-linux-stemcell-builder#162]
#### Description

Once the community Concourse has been setup, let's move the necessary pipelines over. This includes retrieving the necessary credentials form VMWare.

#### Questions

- So far there are AWS S3 blobstores used for several artifacts. Would it make sense to use instead GCS blobstores instead where possible?
- Would we need a new repository for this?

#### Context

- a rough overview of the assets has been collected in https://docs.google.com/document/d/1846mRZ1X-Z5mv0ayHykp2N7B7aT1fujEGV-ntuVxO98
  
#### ToDo

- [x]  fix usn log resource
- [ ]  investigate ami push access to aws gov region
- [ ] setup publish pipeline
- [ ] ..

#### Acceptance Criteria

- the pipelines are capable to release candidates for:
  - AliCloud, AWS, Azure, GCP, OpenStack, vSphere, vCloud heavy stemcells 
  -  AWS, GCP light stemcells

**Comment by ramonskie** [comment]
i thought they used a different account for that.
but i think you can request it just for your account

**Comment by yatzek** [comment]
First stemcell has been successfully released from the community owned  pipeline - 1.10 version. Closing this ticket.

**Comment by friegger** [comment]
@ramonskie From this issue I cannot discover what work has been done and what changes have been made. Can you complete the todo list and link to relevant changes/repos?

**Comment by ramonskie** [comment]
the PR https://github.com/cloudfoundry/bosh-stemcells-ci/pull/4
