### ISSUE TITLE
Provide basic infrastructure to support Ubuntu Focal

### ISSUE THREAD

**Issue by StefanWutz** [cloudfoundry/bosh-linux-stemcell-builder#184]
Provide support for Ubuntu Focal

# Tasks:
- [x] Create a new branch ubuntu-focal/master
- [x] Add build environment for focal
- [x] Update rspec tests to support
- [x] Remove stage system_ixgbevf stage. Driver ixgbevf will be provided by kernel module
- [x] Update package list to build a focal os image
- [ ] Build stemcell variants
- [ ] Revise logrotate configuration file
 
# Changes:

- The current version VMWare Ovftool does not work with Ubuntu Focal. Using the latest version VMware-ovftool-4.4.1-16812187-lin.x86_64.bundle will work.
- Removed installation of intel ixgbevf driver from source using the kernel module instead.

**Comment by bgandon** [comment]
Highly in favor for providing experimental Focal Stemcells 👍
